export const allMakesModels = [
  {
    id: 1,
    make: "Acura",
    models: ["ILX", "Integra", "MDX", "NSX", "RDX", "TLX "],
  },
  {
    id: 2,
    make: "Alfa Romeo",
    models: ["Giulia", "Stelvio", "Tonale"],
  },
  {
    id: 3,
    make: "Aston Martin",
    models: ["DB11", "DBS", "DBS Superleggera", "DBX", "Vantage"],
  },
  {
    id: 4,
    make: "Audi",
    models: [
      "A3",
      "A4",
      "A4 allroad",
      "A5",
      "A6",
      "A6 allroad",
      "A7",
      "A8",
      "e-tron",
      "e-tron GT",
      "e-tron S",
      "e-tron S Sportback",
      "e-tron Sportback",
      "Q3",
      "Q4 e-tron",
      "Q4 Sportback e-tron",
      "Q5",
      "Q5 Sportback",
      "Q7",
      "Q8",
      "R8",
      "RS 3",
      "RS 5",
      "RS 6",
      "RS 7",
      "RS e-tron GT",
      "RS Q8",
      "S3",
      "S4",
      "S5",
      "S6",
      "S7",
      "S8",
      "SQ5",
      "SQ5 Sportback",
      "SQ7",
      "SQ8",
      "TT",
    ],
  },
  {
    id: 5,
    make: "Bentley",
    models: ["Bentayga", "Continental GT", "Flying Spur"],
  },
  {
    id: 6,
    make: "BMW",
    models: [
      "2 Series",
      "3 Series",
      "4 Series",
      "5 Series",
      "7 Series",
      "8 Series",
      "i3",
      "i4",
      "i7",
      "iX",
      "M2",
      "M3",
      "M4",
      "M5",
      "M8",
      "X1",
      "X2",
      "X3",
      "X3 M",
      "X4",
      "X4 M",
      "X5",
      "X5 M",
      "X6",
      "X6 M",
      "X7",
      "XM",
      "Z4",
    ],
  },
  {
    id: 7,
    make: "Buick",
    models: ["Enclave", "Encore", "Encore GX", "Envision"],
  },
  {
    id: 8,
    make: "Cadillac",
    models: [
      "Celestiq",
      "CT4",
      "CT5",
      "Escalade",
      "Escalade ESV",
      "LYRIQ",
      "XT4",
      "XT5",
      "XT6",
    ],
  },
  {
    id: 9,
    make: "Chevrolet",
    models: [
      "Blazer",
      "Blazer EV",
      "Bolt EUV",
      "Bolt EV",
      "Camaro",
      "Colorado Crew Cab",
      "Colorado Extended Cab",
      "Corvette",
      "Equinox",
      "Equinox EV",
      "Express 2500 Cargo",
      "Express 2500 Passenger",
      "Express 3500 Cargo",
      "Express 3500 Passenger",
      "Malibu",
      "Silverado 1500 Crew Cab",
      "Silverado 1500 Double Cab",
      "Silverado 1500 Limited Crew Cab",
      "Silverado 1500 Limited Double Cab",
      "Silverado 1500 Limited Regular Cab",
      "Silverado 1500 Regular Cab",
      "Silverado 2500 HD Crew Cab",
      "Silverado 2500 HD Double Cab",
      "Silverado 2500 HD Regular Cab",
      "Silverado 3500 HD Crew Cab",
      "Silverado 3500 HD Double Cab",
      "Silverado 3500 HD Regular Cab",
      "Silverado EV",
      "Spark",
      "Suburban",
      "Tahoe",
      "Trailblazer",
      "Traverse",
      "Trax",
    ],
  },
  {
    id: 10,
    make: "Chrysler",
    models: ["300", "Pacifica", "Pacifica Hybrid", "Voyager"],
  },
  {
    id: 11,
    make: "Dodge",
    models: ["Challenger", "Charger", "Durango", "Hornet"],
  },
  {
    id: 12,
    make: "Ferrari",
    models: [
      "296 GTB",
      "488 Pista",
      "812 Competizione",
      "812 Competizione A",
      "812 GTS",
      "812 Superfast",
      "F8",
      "Portofino",
      "Roma",
      "SF90",
    ],
  },
  {
    id: 13,
    make: "Fiat",
    models: ["500X"],
  },
  {
    id: 14,
    make: "Ford",
    models: [
      "Bronco",
      "Bronco Sport",
      "E-Transit 350 Cargo Van",
      "EcoSport",
      "Edge",
      "Escape",
      "Escape Plug-in Hybrid",
      "Expedition",
      "Expedition MAX",
      "Explorer",
      "F150 Lightning",
      "F150 Regular Cab",
      "F150 Super Cab",
      "F150 SuperCrew Cab",
      "F250 Super Duty Crew Cab",
      "F250 Super Duty Regular Cab",
      "F250 Super Duty Super Cab",
      "F350 Super Duty Crew Cab",
      "F350 Super Duty Regular Cab",
      "F350 Super Duty Super Cab",
      "F450 Super Duty Crew Cab",
      "F450 Super Duty Regular Cab",
      "Maverick",
      "Mustang",
      "Mustang MACH-E",
      "Ranger SuperCab",
      "Ranger SuperCrew",
      "Transit 150 Cargo Van",
      "Transit 150 Crew Van",
      "Transit 150 Passenger Van",
      "Transit 250 Cargo Van",
      "Transit 250 Crew Van",
      "Transit 350 Cargo Van",
      "Transit 350 Crew Van",
      "Transit 350 HD Cargo Van",
      "Transit 350 HD Crew Van",
      "Transit 350 Passenger Van",
      "Transit Connect Cargo Van",
      "Transit Connect Passenger Wagon",
    ],
  },
  {
    id: 15,
    make: "Freightliner",
    models: [
      "Sprinter 1500 Cargo",
      "Sprinter 1500 Passenger",
      "Sprinter 2500 Cargo",
      "Sprinter 2500 Crew",
      "Sprinter 2500 Passenger",
      "Sprinter 3500 Cargo",
      "Sprinter 3500 Crew",
      "Sprinter 3500 XD Crew",
      "Sprinter 3500XD Cargo",
      "Sprinter 4500 Cargo",
      "Sprinter 4500 Crew",
    ],
  },
  {
    id: 16,
    make: "Genesis",
    models: ["Electrified G80", "G70", "G80", "G90", "GV60", "GV70", "GV80"],
  },
  {
    id: 17,
    make: "GMC",
    models: [
      "Acadia",
      "Canyon Crew Cab",
      "Canyon Extended Cab",
      "Hummer EV Pickup",
      "Hummer EV SUV",
      "024 Savana 2500 Cargo",
      "Savana 2500 Passenger",
      "Savana 3500 Cargo",
      "Savana 3500 Passenger",
      "Sierra 1500 Crew Cab",
      "Sierra 1500 Double Cab",
      "Sierra 1500 Limited Crew Cab",
      "Sierra 1500 Limited Double Cab",
      "Sierra 1500 Limited Regular Cab",
      "Sierra 1500 Regular Cab",
      "Sierra 2500 HD Crew Cab",
      "Sierra 2500 HD Double Cab",
      "Sierra 2500 HD Regular Cab",
      "Sierra 3500 HD Crew Cab",
      "Sierra 3500 HD Double Cab",
      "Sierra 3500 HD Regular Cab",
      "Terrain",
      "Yukon",
      "Yukon XL",
    ],
  },
  {
    id: 18,
    make: "Honda",
    models: [
      "Accord",
      "Accord Hybrid",
      "Civic",
      "Civic Type R",
      "Clarity Fuel Cell",
      "Clarity Plug-in Hybrid",
      "CR-V",
      "CR-V Hybrid",
      "HR-V",
      "Insight",
      "Odyssey",
      "Passport",
      "Pilot",
      "Prologue",
      "Ridgeline",
    ],
  },
  {
    id: 19,
    make: "Hyundai",
    models: [
      "Accent",
      "Elantra",
      "Elantra Hybrid",
      "Elantra N",
      "IONIQ 5",
      "IONIQ 6",
      "IONIQ 7",
      "Ioniq Electric",
      "Ioniq Hybrid",
      "Ioniq Plug-in Hybrid",
      "Kona",
      "Kona Electric",
      "Kona N",
      "NEXO",
      "Palisade",
      "Santa Cruz",
      "Santa Fe",
      "Santa Fe Hybrid",
      "Santa Fe Plug-in Hybrid",
      "Sonata",
      "Sonata Hybrid",
      "Tucson",
      "Tucson Hybrid",
      "Tucson Plug-in Hybrid",
      "Veloster",
      "Venue",
    ],
  },
  {
    id: 20,
    make: "INFINTI",
    model: ["Q50", "Q60", "QX50", "QX55", "QX60", "QX80"],
  },
  {
    id: 21,
    make: "Jaguar",
    models: ["E-PACE", "F-PACE", "F-TYPE", "I-PACE", "XF"],
  },
  {
    id: 22,
    make: "Jeep",
    models: [
      "Cherokee",
      "Compass",
      "Gladiator",
      "Grand Cherokee",
      "Grand Cherokee 4xe",
      "Grand Cherokee L",
      "Grand Wagoneer",
      "Grand Wagoneer L",
      "Recon",
      "024 Renegade",
      "Wagoneer",
      "Wagoneer L",
      "Wrangler",
      "Wrangler Unlimited",
      "Wrangler Unlimited 4xe",
    ],
  },
  {
    id: 23,
    make: "Kia",
    models: [
      "Carnival",
      "EV6",
      "EV9",
      "Forte",
      "K5",
      "Niro",
      "Niro EV",
      "Niro Plug-in Hybrid",
      "Rio",
      "Sedona",
      "Seltos",
      "Sorento",
      "Sorento Hybrid",
      "Sorento Plug-in Hybrid",
      "Soul",
      "Sportage",
      "Sportage Hybrid",
      "Sportage Plug-in Hybrid",
      "Stinger",
      "Telluride",
    ],
  },
  {
    id: 24,
    make: "Lamborghini",
    models: ["Aventador", "Huracan", "Urus"],
  },
  {
    id: 25,
    make: "Land Rover",
    models: [
      "Defender 110",
      "Defender 130",
      "Defender 90",
      "Discovery",
      "Discovery Sport",
      "Range Rover",
      "Range Rover Evoque",
      "Range Rover Sport",
      "Range Rover Velar",
    ],
  },
  {
    id: 26,
    make: "Lexus",
    models: [
      "ES",
      "GX",
      "IS",
      "LC",
      "LS",
      "LX",
      "NX",
      "RC",
      "RX",
      "RZ",
      "TX",
      "UX",
    ],
  },
  {
    id: 27,
    make: "Lincoln",
    models: ["Aviator", "Corsair", "Nautilus", "Navigator", "Navigator L"],
  },
  {
    id: 28,
    make: "Lotus",
    models: ["Evora GT"],
  },
  {
    id: 29,
    make: "Lucid",
    models: ["Air"],
  },
  {
    id: 30,
    make: "Maserati",
    models: ["Ghibli", "Grecale", "Levante", "MC20", "Quattroporte"],
  },
  {
    id: 31,
    make: "Mazda",
    models: [
      "CX-3",
      "CX-30",
      "CX-5",
      "CX-50",
      "CX-70",
      "2024 CX-9",
      "CX-90",
      "3",
      "6",
      "MX-30",
      "MX-5 Miata",
      "MX-5 Miata RF",
    ],
  },
  {
    id: 32,
    make: "Mercedes-Benz",
    models: [
      "A-Class",
      "C-Class",
      "CLA",
      "CLS",
      "E-Class",
      "G-Class",
      "GLA",
      "GLB",
      "GLC",
      "GLC Coupe",
      "GLE",
      "GLS",
      "AMG A-Class",
      "AMG C-Class",
      "AMG CLA",
      "AMG CLS",
      "AMG E-Class",
      "AMG EQS",
      "AMG G-Class",
      "AMG GLA",
      "AMG GLB",
      "AMG GLC",
      "AMG GLC Coupe",
      "AMG GLE",
      "AMG GLE Coupe",
      "AMG GLS",
      "AMG GT",
      "AMG S-Class",
      "AMG SL",
      "EQ EQB",
      "EQ EQE",
      "EQ EQE SUV",
      "EQ EQS",
      "EQ EQS SUV",
      "Maybach GLS",
      "Maybach S-Class",
      "Metris Cargo",
      "Metris Passenger",
      "S-Class",
      "Sprinter 1500 Cargo",
      "Sprinter 1500 Passenger",
      "Sprinter 2500 Cargo",
      "Sprinter 2500 Crew",
      "Sprinter 2500 Passenger",
      "Sprinter 3500 Cargo",
      "Sprinter 3500 Crew",
      "Sprinter 3500 XD Cargo",
      "Sprinter 3500 XD Crew",
      "Sprinter 4500 Cargo",
      "Sprinter 4500 Crew",
    ],
  },
  {
    id: 33,
    make: "MINI",
    models: [
      "Clubman",
      "Convertible",
      "Countryman",
      "Hardtop 2 Door",
      "Hardtop 4 Door",
    ],
  },
  {
    id: 34,
    make: "Mitsubishi",
    models: [
      "Eclipse Cross",
      "Mirage",
      "Mirage G4",
      "Outlander",
      "Outlander PHEV",
      "Outlander Sport",
    ],
  },
  {
    id: 35,
    make: "Nissan",
    models: [
      "400Z",
      "Altima",
      "Ariya",
      "Armada",
      "Frontier Crew Cab",
      "Frontier King Cab",
      "GT-R",
      "Kicks",
      "LEAF",
      "Maxima",
      "Murano",
      "NV1500 Cargo",
      "NV200",
      "NV2500 HD Cargo",
      "NV3500 HD Cargo",
      "NV3500 HD Passenger",
      "Pathfinder",
      "Rogue",
      "Rogue Sport",
      "Sentra",
      "Titan Crew Cab",
      "Titan King Cab",
      "TITAN XD Crew Cab",
      "Versa",
      "Z",
    ],
  },
  {
    id: 36,
    make: "Polestar",
    models: ["1", "2", "3", "5"],
  },
  {
    id: 37,
    make: "Porsche",
    models: [
      "718 Boxster",
      "718 Cayman",
      "718 Spyder",
      "911",
      "Cayenne",
      "Cayenne Coupe",
      "Macan",
      "Panamera",
      "Taycan",
      "Taycan Cross Turismo",
    ],
  },
  {
    id: 38,
    make: "Ram",
    models: [
      "1500 Classic Crew Cab",
      "1500 Classic Quad Cab",
      "1500 Classic Regular Cab",
      "1500 Crew Cab",
      "1500 Quad Cab",
      "2500 Crew Cab",
      "2500 Mega Cab",
      "2500 Regular Cab",
      "3500 Crew Cab",
      "3500 Mega Cab",
      "3500 Regular Cab",
      "ProMaster Cargo Van",
      "ProMaster City",
      "ProMaster Window Van",
    ],
  },
  {
    id: 39,
    make: "Rivian",
    models: ["R1S", "R1T"],
  },
  {
    id: 40,
    make: "Rolls-Royce",
    models: ["Cullinan", "Dawn", "Ghost", "Phantom", "Wraith"],
  },
  {
    id: 41,
    make: "Subaru",
    models: [
      "Ascent",
      "BRZ",
      "Crosstrek",
      "Forester",
      "Impreza",
      "Legacy",
      "Outback",
      "Solterra",
      "WRX",
    ],
  },
  {
    id: 42,
    make: "Tesla",
    models: ["Cybertruck", "Model 3", "Model S", "Model X", "Model Y"],
  },
  {
    id: 43,
    make: "Toyota",
    models: [
      "4Runner",
      "86",
      "Avalon",
      "Avalon Hybrid",
      "bZ4X",
      "C-HR",
      "Camry",
      "Camry Hybrid",
      "Corolla",
      "Corolla Cross",
      "Corolla Cross Hybrid",
      "Corolla Hatchback",
      "Corolla Hybrid",
      "Crown",
      "GR Supra",
      "GR86",
      "Highlander",
      "Highlander Hybrid",
      "Land Cruiser",
      "Mirai",
      "Prius",
      "Prius Prime",
      "RAV4",
      "RAV4 Hybrid",
      "RAV4 Prime",
      "Sequoia",
      "Sienna",
      "Tacoma Access Cab",
      "Tacoma Double Cab",
      "Tundra CrewMax",
      "Tundra Double Cab",
      "Tundra Hybrid CrewMax",
      "Venza",
    ],
  },
  {
    id: 44,
    make: "VinFast",
    models: ["VF 8", "VF 9"],
  },
  {
    id: 45,
    make: "Volkswagen",
    models: [
      "Arteon",
      "Atlas",
      "Atlas Cross Sport",
      "Golf",
      "Golf GTI",
      "Golf R",
      "ID.4",
      "ID.Buzz",
      "Jetta",
      "Jetta GLI",
      "Passat",
      "Taos",
      "Tiguan",
    ],
  },
  {
    id: 46,
    make: "Volvo",
    models: [
      "C40 Recharge",
      "EX90",
      "S60",
      "S90",
      "V60",
      "V90",
      "XC40",
      "XC40 Recharge",
      "XC60",
      "XC90",
    ],
  },
];

export const DUMMY_CARS = [
  {
    id: "0",
    isStock: "true",
    status: "available",
    listing: {
      listingId: "000018963",
      listingOwnerId: "user0000",
      createdAt: new Date("October 3, 2022, 14:45"),
    },
    condition: "used",
    year: "2018",
    make: "Honda",
    model: "Accord",
    trim: "Sport",
    engine: {
      electric: false,
      capacity: "2.0L",
      cylinders: "4",
      horsepower: "186",
      torque: "175",
    },
    transmission: "automatic",
    miles: "12508",
    price: "32456",
    extColor: "white",
    intColor: "black",
    location: {
      city: "Boston",
      state: "MA",
      zip: "02108",
    },
    pictures: [
      "https://source.unsplash.com/random/?car/1235462",
      "https://source.unsplash.com/random/?car/14536",
      "https://source.unsplash.com/random/?car/1354464",
      "https://source.unsplash.com/random/?car/515465",
      "https://source.unsplash.com/random/?car/175663",
    ],
  },
  {
    id: "1",
    isStock: "true",
    status: "available",
    listing: {
      listingId: "00012668",
      listingOwnerId: "user0001",
      createdAt: new Date("October 21, 2022, 14:45"),
    },
    condition: "used",
    year: "2019",
    make: "Tesla",
    model: "Model S",
    trim: "Plaid Performante Nationale",
    engine: {
      electric: true,
      capacity: "95Kwh",
      cylinders: "0",
      horsepower: "987",
      torque: "1056",
    },
    transmission: "automatic",
    miles: "7965",
    price: "148900",
    extColor: "white",
    intColor: "black",
    location: {
      city: "Brooklyn",
      state: "NY",
      zip: "15489",
    },
    pictures: [
      "https://source.unsplash.com/random/?car/12346227",
      "https://source.unsplash.com/random/?car/14368",
      "https://source.unsplash.com/random/?car/134465",
      "https://source.unsplash.com/random/?car/15466",
      "https://source.unsplash.com/random/?car/176631",
    ],
  },
  {
    id: "2",
    isStock: "true",
    status: "available",
    listing: {
      listingId: "00023114",
      listingOwnerId: "user0002",
      createdAt: new Date("October 7, 2022, 14:45"),
    },
    condition: "used",
    year: "2020",
    make: "Mercedes",
    model: "C300",
    trim: "Elegance",
    engine: {
      capacity: "3.0L",
      cylinders: "6",
      horsepower: "245",
      torque: "260",
    },
    transmission: "automatic",
    miles: "8000",
    price: "56500",
    extColor: "white",
    intColor: "black",
    location: {
      city: "Newton",
      state: "PA",
      zip: "56987",
    },
    pictures: [
      "https://source.unsplash.com/random/?car/12346219",
      "https://source.unsplash.com/random/?car/143619",
      "https://source.unsplash.com/random/?car/1344619",
      "https://source.unsplash.com/random/?car/154619",
      "https://source.unsplash.com/random/?car/1766319",
    ],
  },
  {
    id: "3",
    isStock: "true",
    status: "available",
    listing: {
      listingId: "00034078",
      listingOwnerId: "user0003",
      createdAt: new Date("October 11, 2022, 14:45"),
    },
    condition: "used",
    year: "2021",
    make: "Audi",
    model: "A6",
    trim: "Premium",
    engine: {
      capacity: "3.2L",
      cylinders: "6",
      horsepower: "298",
      torque: "315",
    },
    transmission: "automatic",
    miles: "6458",
    price: "75485",
    extColor: "white",
    intColor: "black",
    location: {
      city: "Fairfax",
      state: "VA",
      zip: "36521",
    },
    pictures: [
      "https://source.unsplash.com/random/?car/12346267",
      "https://source.unsplash.com/random/?car/143667",
      "https://source.unsplash.com/random/?car/1344667",
      "https://source.unsplash.com/random/?car/154667",
      "https://source.unsplash.com/random/?car/1766367",
    ],
  },
  {
    id: "4",
    isStock: "true",
    status: "available",
    listing: {
      listingId: "00045045",
      listingOwnerId: "user0004",
      createdAt: new Date("August 28, 2022, 14:45"),
    },
    condition: "new",
    year: "2022",
    make: "Hyundai",
    model: "Sonata",
    trim: "Limited",
    engine: {
      capacity: "1.6L",
      cylinders: "4",
      horsepower: "186",
      torque: "195",
    },
    transmission: "automatic",
    miles: "0",
    price: "39879",
    extColor: "white",
    intColor: "black",
    location: {
      city: "Farmingville",
      state: "NY",
      zip: "11738",
    },
    pictures: [
      "https://source.unsplash.com/random/?car/12346225",
      "https://source.unsplash.com/random/?car/143625",
      "https://source.unsplash.com/random/?car/1344625",
      "https://source.unsplash.com/random/?car/154625",
      "https://source.unsplash.com/random/?car/1766325",
    ],
  },
  {
    id: "5",
    isStock: "true",
    status: "available",
    listing: {
      listingId: "00056773",
      listingOwnerId: "user0005",
      createdAt: new Date("May 22, 2022, 14:45"),
    },
    condition: "used",
    year: "2016",
    make: "Honda",
    model: "HR-V",
    trim: "EX-L",
    engine: {
      capacity: "2.0L",
      cylinders: "4",
      horsepower: "192",
      torque: "198",
    },
    transmission: "automatic",
    miles: "4256",
    price: "42565",
    extColor: "white",
    intColor: "black",
    location: {
      city: "Syracuse",
      state: "NY",
      zip: "56256",
    },
    pictures: [
      "https://source.unsplash.com/random/?car/12346287",
      "https://source.unsplash.com/random/?car/143687",
      "https://source.unsplash.com/random/?car/1344678",
      "https://source.unsplash.com/random/?car/154678",
      "https://source.unsplash.com/random/?car/1766387",
    ],
  },
  {
    id: "6",
    isStock: "true",
    status: "available",
    listing: {
      listingId: "00007078",
      listingOwnerId: "user0000",
      createdAt: new Date("February 16, 2022, 14:45"),
    },
    condition: "used",
    year: "2018",
    make: "Honda",
    model: "Accord",
    trim: "Sport",
    engine: {
      electric: false,
      capacity: "2.0L",
      cylinders: "4",
      horsepower: "186",
      torque: "175",
    },
    transmission: "automatic",
    miles: "12508",
    price: "32456",
    extColor: "white",
    intColor: "black",
    location: {
      city: "Boston",
      state: "MA",
      zip: "02108",
    },
    pictures: [
      "https://source.unsplash.com/random/?car/12346245",
      "https://source.unsplash.com/random/?car/143645",
      "https://source.unsplash.com/random/?car/1344456",
      "https://source.unsplash.com/random/?car/154645",
      "https://source.unsplash.com/random/?car/1766345",
    ],
  },
  {
    id: "7",
    isStock: "true",
    status: "available",
    listing: {
      listingId: "00018692",
      listingOwnerId: "user0001",
      createdAt: new Date("August 04, 2022, 14:45"),
    },
    condition: "used",
    year: "2019",
    make: "Tesla",
    model: "Model S",
    trim: "Plaid Performante Nationale",
    engine: {
      electric: true,
      capacity: "95Kwh",
      cylinders: "0",
      horsepower: "987",
      torque: "1056",
    },
    transmission: "automatic",
    miles: "7965",
    price: "148900",
    extColor: "white",
    intColor: "black",
    location: {
      city: "Brooklyn",
      state: "NY",
      zip: "15489",
    },
    pictures: [
      "https://source.unsplash.com/random/?car/12346246",
      "https://source.unsplash.com/random/?car/1436436",
      "https://source.unsplash.com/random/?car/13446463",
      "https://source.unsplash.com/random/?car/1546463",
      "https://source.unsplash.com/random/?car/17663463",
    ],
  },
  {
    id: "8",
    isStock: "true",
    status: "available",
    listing: {
      listingId: "0002904",
      listingOwnerId: "user0002",
      createdAt: new Date("July 08, 2022, 14:45"),
    },
    condition: "used",
    year: "2020",
    make: "Mercedes",
    model: "C300",
    trim: "Elegance",
    engine: {
      capacity: "3.0L",
      cylinders: "6",
      horsepower: "245",
      torque: "260",
    },
    transmission: "automatic",
    miles: "8000",
    price: "56500",
    extColor: "white",
    intColor: "black",
    location: {
      city: "Newton",
      state: "PA",
      zip: "56987",
    },
    pictures: [
      "https://source.unsplash.com/random/?car/12346243",
      "https://source.unsplash.com/random/?car/143643",
      "https://source.unsplash.com/random/?car/1344643",
      "https://source.unsplash.com/random/?car/154643",
      "https://source.unsplash.com/random/?car/1766343",
    ],
  },
  {
    id: "9",
    isStock: "true",
    status: "available",
    listing: {
      listingId: "00031787",
      listingOwnerId: "user0003",
      createdAt: new Date("June 26, 2022, 14:45"),
    },
    condition: "used",
    year: "2021",
    make: "Audi",
    model: "A6",
    trim: "Premium",
    engine: {
      capacity: "3.2L",
      cylinders: "6",
      horsepower: "298",
      torque: "315",
    },
    transmission: "automatic",
    miles: "6458",
    price: "75485",
    extColor: "white",
    intColor: "black",
    location: {
      city: "Fairfax",
      state: "VA",
      zip: "36521",
    },
    pictures: [
      "https://source.unsplash.com/random/?car/12346224",
      "https://source.unsplash.com/random/?car/143624",
      "https://source.unsplash.com/random/?car/1344624",
      "https://source.unsplash.com/random/?car/154624",
      "https://source.unsplash.com/random/?car/1766324",
    ],
  },
  {
    id: "10",
    isStock: "true",
    status: "available",
    listing: {
      listingId: "00042632",
      listingOwnerId: "user0004",
      createdAt: new Date("March 11, 2022, 14:45"),
    },
    condition: "new",
    year: "2022",
    make: "Hyundai",
    model: "Sonata",
    trim: "Limited",
    engine: {
      capacity: "1.6L",
      cylinders: "4",
      horsepower: "186",
      torque: "195",
    },
    transmission: "automatic",
    miles: "0",
    price: "39879",
    extColor: "white",
    intColor: "black",
    location: {
      city: "Farmingville",
      state: "NY",
      zip: "11738",
    },
    pictures: [
      "https://source.unsplash.com/random/?car/12346223",
      "https://source.unsplash.com/random/?car/143623",
      "https://source.unsplash.com/random/?car/1344623",
      "https://source.unsplash.com/random/?car/154623",
      "https://source.unsplash.com/random/?car/1766323",
    ],
  },
  {
    id: "11",
    isStock: "true",
    status: "available",
    listing: {
      listingId: "00053784",
      listingOwnerId: "user0005",
      createdAt: new Date("April 12, 2022, 14:45"),
    },
    condition: "used",
    year: "2016",
    make: "Honda",
    model: "HR-V",
    trim: "EX-L",
    engine: {
      capacity: "2.0L",
      cylinders: "4",
      horsepower: "192",
      torque: "198",
    },
    transmission: "automatic",
    miles: "4256",
    price: "42565",
    discounted: "39900",
    extColor: "white",
    intColor: "black",
    location: {
      city: "Syracuse",
      state: "NY",
      zip: "56256",
    },
    pictures: [
      "https://source.unsplash.com/random/?car/12346222",
      "https://source.unsplash.com/random/?car/143622",
      "https://source.unsplash.com/random/?car/1344622",
      "https://source.unsplash.com/random/?car/154622",
      "https://source.unsplash.com/random/?car/1766322",
    ],
  },
  {
    id: "12",
    isStock: "true",
    status: "available",
    listing: {
      listingId: "0000107",
      listingOwnerId: "user0000",
      createdAt: new Date("October 3, 2022, 14:45"),
    },
    condition: "used",
    year: "2018",
    make: "Honda",
    model: "Accord",
    trim: "Sport",
    engine: {
      electric: false,
      capacity: "2.0L",
      cylinders: "4",
      horsepower: "186",
      torque: "175",
    },
    transmission: "automatic",
    miles: "12508",
    price: "32456",
    extColor: "white",
    intColor: "black",
    location: {
      city: "Boston",
      state: "MA",
      zip: "02108",
    },
    pictures: [
      "https://source.unsplash.com/random/?car/12346221",
      "https://source.unsplash.com/random/?car/143621",
      "https://source.unsplash.com/random/?car/1344621",
      "https://source.unsplash.com/random/?car/154621",
      "https://source.unsplash.com/random/?car/1766321",
    ],
  },
  {
    id: "13",
    isStock: "true",
    status: "available",
    listing: {
      listingId: "0001298",
      listingOwnerId: "user0001",
      createdAt: new Date("October 21, 2022, 14:45"),
    },
    condition: "used",
    year: "2019",
    make: "Tesla",
    model: "Model S",
    trim: "Plaid Performante Nationale",
    engine: {
      electric: true,
      capacity: "95Kwh",
      cylinders: "0",
      horsepower: "987",
      torque: "1056",
    },
    transmission: "automatic",
    miles: "7965",
    price: "148900",
    extColor: "white",
    intColor: "black",
    location: {
      city: "Brooklyn",
      state: "NY",
      zip: "15489",
    },
    pictures: [
      "https://source.unsplash.com/random/?car/1234620",
      "https://source.unsplash.com/random/?car/14360",
      "https://source.unsplash.com/random/?car/134460",
      "https://source.unsplash.com/random/?car/15460",
      "https://source.unsplash.com/random/?car/176630",
    ],
  },
  {
    id: "14",
    isStock: "true",
    status: "available",
    listing: {
      listingId: "0002368",
      listingOwnerId: "user0002",
      createdAt: new Date("October 7, 2022, 14:45"),
    },
    condition: "used",
    year: "2020",
    make: "Mercedes",
    model: "C300",
    trim: "Elegance",
    engine: {
      capacity: "3.0L",
      cylinders: "6",
      horsepower: "245",
      torque: "260",
    },
    transmission: "automatic",
    miles: "8000",
    price: "56500",
    extColor: "white",
    intColor: "black",
    location: {
      city: "Newton",
      state: "PA",
      zip: "56987",
    },
    pictures: [
      "https://source.unsplash.com/random/?car/1234692",
      "https://source.unsplash.com/random/?car/14396",
      "https://source.unsplash.com/random/?car/134469",
      "https://source.unsplash.com/random/?car/15469",
      "https://source.unsplash.com/random/?car/176639",
    ],
  },
  {
    id: "15",
    isStock: "true",
    status: "available",
    listing: {
      listingId: "0003478",
      listingOwnerId: "user0003",
      createdAt: new Date("October 11, 2022, 14:45"),
    },
    condition: "used",
    year: "2021",
    make: "Audi",
    model: "A6",
    trim: "Premium",
    engine: {
      capacity: "3.2L",
      cylinders: "6",
      horsepower: "298",
      torque: "315",
    },
    transmission: "automatic",
    miles: "6458",
    price: "75485",
    extColor: "white",
    intColor: "black",
    location: {
      city: "Fairfax",
      state: "VA",
      zip: "36521",
    },
    pictures: [
      "https://source.unsplash.com/random/?car/1234682",
      "https://source.unsplash.com/random/?car/14368",
      "https://source.unsplash.com/random/?car/134468",
      "https://source.unsplash.com/random/?car/15468",
      "https://source.unsplash.com/random/?car/176638",
    ],
  },
  {
    id: "16",
    isStock: "true",
    status: "available",
    listing: {
      listingId: "0004504",
      listingOwnerId: "user0004",
      createdAt: new Date("August 28, 2022, 14:45"),
    },
    condition: "new",
    year: "2022",
    make: "Hyundai",
    model: "Sonata",
    trim: "Limited",
    engine: {
      capacity: "1.6L",
      cylinders: "4",
      horsepower: "186",
      torque: "195",
    },
    transmission: "automatic",
    miles: "0",
    price: "39879",
    extColor: "white",
    intColor: "black",
    location: {
      city: "Farmingville",
      state: "NY",
      zip: "11738",
    },
    pictures: [
      "https://source.unsplash.com/random/?car/1234627",
      "https://source.unsplash.com/random/?car/14367",
      "https://source.unsplash.com/random/?car/134467",
      "https://source.unsplash.com/random/?car/15467",
      "https://source.unsplash.com/random/?car/176637",
    ],
  },
  {
    id: "17",
    isStock: "true",
    status: "available",
    listing: {
      listingId: "0005669",
      listingOwnerId: "user0005",
      createdAt: new Date("May 22, 2022, 14:45"),
    },
    condition: "used",
    year: "2016",
    make: "Honda",
    model: "HR-V",
    trim: "EX-L",
    engine: {
      capacity: "2.0L",
      cylinders: "4",
      horsepower: "192",
      torque: "198",
    },
    transmission: "automatic",
    miles: "4256",
    price: "42565",
    extColor: "white",
    intColor: "black",
    location: {
      city: "Syracuse",
      state: "NY",
      zip: "56256",
    },
    pictures: [
      "https://source.unsplash.com/random/?car/1234626",
      "https://source.unsplash.com/random/?car/14366",
      "https://source.unsplash.com/random/?car/134466",
      "https://source.unsplash.com/random/?car/15466",
      "https://source.unsplash.com/random/?car/176636",
    ],
  },
  {
    id: "18",
    isStock: "true",
    status: "available",
    listing: {
      listingId: "0000704",
      listingOwnerId: "user0000",
      createdAt: new Date("February 16, 2022, 14:45"),
    },
    condition: "used",
    year: "2018",
    make: "Honda",
    model: "Accord",
    trim: "Sport",
    engine: {
      electric: false,
      capacity: "2.0L",
      cylinders: "4",
      horsepower: "186",
      torque: "175",
    },
    transmission: "automatic",
    miles: "12508",
    price: "32456",
    extColor: "white",
    intColor: "black",
    location: {
      city: "Boston",
      state: "MA",
      zip: "02108",
    },
    pictures: [
      "https://source.unsplash.com/random/?car/1234625",
      "https://source.unsplash.com/random/?car/14365",
      "https://source.unsplash.com/random/?car/134465",
      "https://source.unsplash.com/random/?car/15465",
      "https://source.unsplash.com/random/?car/176635",
    ],
  },
  {
    id: "19",
    isStock: "true",
    status: "available",
    listing: {
      listingId: "0001865",
      listingOwnerId: "user0001",
      createdAt: new Date("August 04, 2022, 14:45"),
    },
    condition: "used",
    year: "2019",
    make: "Tesla",
    model: "Model S",
    trim: "Plaid Performante Nationale",
    engine: {
      electric: true,
      capacity: "95Kwh",
      cylinders: "0",
      horsepower: "987",
      torque: "1056",
    },
    transmission: "automatic",
    miles: "7965",
    price: "148900",
    extColor: "white",
    intColor: "black",
    location: {
      city: "Brooklyn",
      state: "NY",
      zip: "15489",
    },
    pictures: [
      "https://source.unsplash.com/random/?car/1234624",
      "https://source.unsplash.com/random/?car/14364",
      "https://source.unsplash.com/random/?car/134464",
      "https://source.unsplash.com/random/?car/15464",
      "https://source.unsplash.com/random/?car/176634",
    ],
  },
  {
    id: "20",
    isStock: "true",
    status: "available",
    listing: {
      listingId: "0002978",
      listingOwnerId: "user0002",
      createdAt: new Date("July 08, 2022, 14:45"),
    },
    condition: "used",
    year: "2020",
    make: "Mercedes",
    model: "C300",
    trim: "Elegance",
    engine: {
      capacity: "3.0L",
      cylinders: "6",
      horsepower: "245",
      torque: "260",
    },
    transmission: "automatic",
    miles: "8000",
    price: "56500",
    extColor: "white",
    intColor: "black",
    location: {
      city: "Newton",
      state: "PA",
      zip: "56987",
    },
    pictures: [
      "https://source.unsplash.com/random/?car/1234623",
      "https://source.unsplash.com/random/?car/14363",
      "https://source.unsplash.com/random/?car/134463",
      "https://source.unsplash.com/random/?car/15463",
      "https://source.unsplash.com/random/?car/176633",
    ],
  },
  {
    id: "21",
    isStock: "true",
    status: "available",
    listing: {
      listingId: "0003145",
      listingOwnerId: "user0003",
      createdAt: new Date("June 26, 2022, 14:45"),
    },
    condition: "used",
    year: "2021",
    make: "Audi",
    model: "A6",
    trim: "Premium",
    engine: {
      capacity: "3.2L",
      cylinders: "6",
      horsepower: "298",
      torque: "315",
    },
    transmission: "automatic",
    miles: "6458",
    price: "75485",
    extColor: "white",
    intColor: "black",
    location: {
      city: "Fairfax",
      state: "VA",
      zip: "36521",
    },
    pictures: [
      "https://source.unsplash.com/random/?car/1234623",
      "https://source.unsplash.com/random/?car/14363",
      "https://source.unsplash.com/random/?car/134463",
      "https://source.unsplash.com/random/?car/15463",
      "https://source.unsplash.com/random/?car/176633",
    ],
  },
  {
    id: "22",
    isStock: "true",
    status: "available",
    listing: {
      listingId: "000428",
      listingOwnerId: "user0004",
      createdAt: new Date("March 11, 2022, 14:45"),
    },
    condition: "new",
    year: "2022",
    make: "Hyundai",
    model: "Sonata",
    trim: "Limited",
    engine: {
      capacity: "1.6L",
      cylinders: "4",
      horsepower: "186",
      torque: "195",
    },
    transmission: "automatic",
    miles: "0",
    price: "39879",
    extColor: "white",
    intColor: "black",
    location: {
      city: "Farmingville",
      state: "NY",
      zip: "11738",
    },
    pictures: [
      "https://source.unsplash.com/random/?car/1234622",
      "https://source.unsplash.com/random/?car/14362",
      "https://source.unsplash.com/random/?car/134462",
      "https://source.unsplash.com/random/?car/15462",
      "https://source.unsplash.com/random/?car/176632",
    ],
  },
  {
    id: "23",
    isStock: "true",
    status: "available",
    listing: {
      listingId: "000536",
      listingOwnerId: "user0005",
      createdAt: new Date("April 12, 2022, 14:45"),
    },
    condition: "used",
    year: "2016",
    make: "Honda",
    model: "HR-V",
    trim: "EX-L",
    engine: {
      capacity: "2.0L",
      cylinders: "4",
      horsepower: "192",
      torque: "198",
    },
    transmission: "automatic",
    miles: "4256",
    price: "42565",
    extColor: "white",
    intColor: "black",
    location: {
      city: "Syracuse",
      state: "NY",
      zip: "56256",
    },
    pictures: [
      "https://source.unsplash.com/random/?car/1234621",
      "https://source.unsplash.com/random/?car/14361",
      "https://source.unsplash.com/random/?car/134461",
      "https://source.unsplash.com/random/?car/15461",
      "https://source.unsplash.com/random/?car/176631",
    ],
  },
];

export const defaultDescription = `Lorem ipsum, or lipsum as it is sometimes known, is dummy
text used in laying out print, graphic or web designs. The
passage is attributed to an unknown typesetter in the 15th
century who is thought to have scrambled parts of Cicero's
De Finibus Bonorum et Malorum for use in a type specimen
book. It usually begins with: “Lorem ipsum dolor sit amet,
consectetur adipiscing elit, sed do eiusmod tempor
incididunt ut labore et dolore magna aliqua.” The purpose
of lorem ipsum is to create a natural looking block of
text (sentence, paragraph, page, etc.) that doesn't
distract from the layout. A practice not without
controversy, laying out pages with meaningless filler text
can be very useful when the focus is meant to be on
design, not content. The passage experienced a surge in
popularity during the 1960s when Letraset used it on their
dry-transfer sheets, and again during the 90s as desktop
publishers bundled the text with their software. Today
it's seen all around the web; on templates, websites, and
stock designs. Use our generator to get your own, or read
on for the authoritative history of lorem ipsum.`;
